/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterMonthlyRouteImport } from './routes/register-monthly'
import { Route as RegisterDailyRouteImport } from './routes/register-daily'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as IndexRouteImport } from './routes/index'

const RegisterMonthlyRoute = RegisterMonthlyRouteImport.update({
  id: '/register-monthly',
  path: '/register-monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterDailyRoute = RegisterDailyRouteImport.update({
  id: '/register-daily',
  path: '/register-daily',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/monitoring': typeof MonitoringRoute
  '/register-daily': typeof RegisterDailyRoute
  '/register-monthly': typeof RegisterMonthlyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/monitoring': typeof MonitoringRoute
  '/register-daily': typeof RegisterDailyRoute
  '/register-monthly': typeof RegisterMonthlyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/monitoring': typeof MonitoringRoute
  '/register-daily': typeof RegisterDailyRoute
  '/register-monthly': typeof RegisterMonthlyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/dashboard'
    | '/login'
    | '/logs'
    | '/monitoring'
    | '/register-daily'
    | '/register-monthly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards'
    | '/dashboard'
    | '/login'
    | '/logs'
    | '/monitoring'
    | '/register-daily'
    | '/register-monthly'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/dashboard'
    | '/login'
    | '/logs'
    | '/monitoring'
    | '/register-daily'
    | '/register-monthly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  MonitoringRoute: typeof MonitoringRoute
  RegisterDailyRoute: typeof RegisterDailyRoute
  RegisterMonthlyRoute: typeof RegisterMonthlyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-monthly': {
      id: '/register-monthly'
      path: '/register-monthly'
      fullPath: '/register-monthly'
      preLoaderRoute: typeof RegisterMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-daily': {
      id: '/register-daily'
      path: '/register-daily'
      fullPath: '/register-daily'
      preLoaderRoute: typeof RegisterDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  MonitoringRoute: MonitoringRoute,
  RegisterDailyRoute: RegisterDailyRoute,
  RegisterMonthlyRoute: RegisterMonthlyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
